import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--color-surface-variant)",
        "on-background": "var(--color-on-background)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "error": "var(--color-error)",
        "secondary-dim": "var(--color-secondary-dim)",
        "primary-dim": "var(--color-primary-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-bright": "var(--color-surface-bright)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "surface": "var(--color-surface)",
        "outline-variant": "var(--color-outline-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-dim": "var(--color-surface-dim)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-dim": "var(--color-tertiary-dim)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "background": "var(--color-background)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "outline": "var(--color-outline)",
        "tertiary": "var(--color-tertiary)",
        "primary-fixed": "var(--color-primary-fixed)",
        "error-dim": "var(--color-error-dim)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-error-container": "var(--color-on-error-container)",
        "on-surface": "var(--color-on-surface)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "error-container": "var(--color-error-container)",
        "secondary-container": "var(--color-secondary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "primary": "var(--color-primary)",
        "surface-container": "var(--color-surface-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)"
      },
      borderRadius: {
        "xl": "0.75rem",
        "2xl": "1.5rem",
      },
      fontFamily: {
        headline: ["var(--font-inter)"],
        body: ["var(--font-public-sans)"],
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
      }
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
